const AUTH_COOKIE='__Host-sm_session';
function cookie(request,name){const raw=request.headers.get('cookie')||'';for(const part of raw.split(';')){const [k,...v]=part.trim().split('=');if(k===name)return v.join('=')}return ''}
const setSessionCookie=token=>`${AUTH_COOKIE}=${token}; Path=/; Secure; HttpOnly; SameSite=Strict`;
const clearSessionCookie=()=>`${AUTH_COOKIE}=; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=0`;
function safeEqual(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function authBackend(request,env,path,body){if(!env.BACKEND_URL||!env.CRM_AUTH_SERVICE_TOKEN)return json({error:'Autenticación no configurada.'},503);const headers={authorization:`Bearer ${env.CRM_AUTH_SERVICE_TOKEN}`,'content-type':'application/json'};const token=cookie(request,AUTH_COOKIE);if(token)headers['x-auth-session']=token;if(request.headers.get('x-csrf-token'))headers['x-csrf-token']=request.headers.get('x-csrf-token');if(env.BACKEND_SITE_AUTH_TOKEN)headers['OAI-Sites-Authorization']=`Bearer ${env.BACKEND_SITE_AUTH_TOKEN}`;try{const r=await fetch(`${env.BACKEND_URL}${path}`,{method:request.method,headers,body});if(!(r.headers.get('content-type')||'').includes('application/json'))return json({error:'El CRM no puede autenticar su conexión privada con el backend de QA.'},502);const data=await r.json().catch(()=>({error:'Respuesta de autenticación inválida.'}));return {r,data}}catch{return json({error:'Backend no disponible.'},503)}}
async function setupStatus(request,env){
  const result=await authBackend(request,env,'/api/internal/auth/setup-status');
  if(result instanceof Response)return result;
  return json(result.data,result.r.status);
}
async function bootstrapAdmin(request,env){
  const url=new URL(request.url);
  if(request.headers.get('origin')&&request.headers.get('origin')!==url.origin)return json({error:'Origen no permitido.'},403);
  const body=await request.text();
  const result=await authBackend(request,env,'/api/internal/auth/bootstrap-admin',body);
  if(result instanceof Response)return result;
  return json(result.data,result.r.status);
}
async function login(request,env){const body=await request.text();const result=await authBackend(request,env,'/api/internal/auth/login',body);if(result instanceof Response)return result;if(!result.r.ok)return json(result.data,result.r.status);return json({ok:true},200,{'set-cookie':setSessionCookie(result.data.token)})}
async function me(request,env){const result=await authBackend(request,env,'/api/internal/auth/me');if(result instanceof Response)return result;return json(result.data,result.r.status)}
async function logout(request,env){const result=await authBackend(request,env,'/api/internal/auth/logout');if(result instanceof Response)return result;return json(result.data,result.r.status,{'set-cookie':clearSessionCookie()})}
async function authenticated(request,env){const result=await authBackend(request,env,'/api/internal/auth/me');if(result instanceof Response||!result.r.ok)return null;return result.data}
const headers={'content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",'referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=()','strict-transport-security':'max-age=31536000; includeSubDomains'};
const json=(d,s=200,extra={})=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers,...extra}});
async function proxy(request,env){if(!env.BACKEND_URL||!env.ADMIN_API_TOKEN||!env.CRM_AUTH_SERVICE_TOKEN)return json({error:'CRM no configurado.'},503);const requestUrl=new URL(request.url);if(requestUrl.pathname==='/api/g3/verification'&&request.method==='POST'&&request.headers.get('origin')!==requestUrl.origin)return json({error:'Origen no permitido.'},403);const user=await authenticated(request,env);if(!user)return json({error:'Inicia sesión para acceder al CRM.'},401);const role=user.role;if(request.method!=='GET'){if(role==='LECTURA')return json({error:'Este rol es de solo lectura.'},403);if(!safeEqual(request.headers.get('x-csrf-token')||'',user.csrf_token))return json({error:'Solicitud no autorizada.'},403);}const url=requestUrl,target=`${env.BACKEND_URL}${url.pathname.replace('/api','/api/admin')}${url.search}`;const init={method:request.method,headers:{authorization:`Bearer ${env.ADMIN_API_TOKEN}`,'x-admin-role':role.toLowerCase(),'x-crm-actor-id':user.id,'content-type':'application/json'}};if(env.BACKEND_SITE_AUTH_TOKEN)init.headers['OAI-Sites-Authorization']=`Bearer ${env.BACKEND_SITE_AUTH_TOKEN}`;if(!['GET','HEAD'].includes(request.method))init.body=await request.text();try{const r=await fetch(target,init);if(!(r.headers.get('content-type')||'').includes('application/json'))return json({error:'El CRM no puede autenticar su conexión privada con el backend de QA.'},502);return new Response(r.body,{status:r.status,headers:{'content-type':r.headers.get('content-type')||'application/json','cache-control':'no-store',...headers}})}catch(e){console.error('proxy failed',e);return json({error:'Backend no disponible.'},503)}}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/auth/setup-status'&&request.method==='GET')return setupStatus(request,env);if(url.pathname==='/api/auth/bootstrap-admin'&&request.method==='POST')return bootstrapAdmin(request,env);if(url.pathname==='/api/auth/login'&&request.method==='POST')return login(request,env);if(url.pathname==='/api/auth/me'&&request.method==='GET')return me(request,env);if(url.pathname==='/api/auth/logout'&&request.method==='POST')return logout(request,env);if(url.pathname.startsWith('/api/'))return proxy(request,env);const asset=ASSETS[url.pathname]||ASSETS['/'];return new Response(asset.body,{headers:{'content-type':asset.type,'cache-control':['/','/index.html','/styles.css','/crm.js','/reminders.js','/g3-flow.js'].includes(url.pathname)?'no-cache':'public, max-age=3600',...headers}})}};
