const AUTH_COOKIE='__Host-sm_session',AUTH_IDLE_MS=30*60*1000,AUTH_ABSOLUTE_MS=8*60*60*1000,AUTH_ITERATIONS=210000;
const bytes=n=>crypto.getRandomValues(new Uint8Array(n));
const b64u=a=>btoa(String.fromCharCode(...a)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const enc=new TextEncoder();
async function digest(value){return b64u(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value))))}
async function passwordHash(password,salt,iterations=AUTH_ITERATIONS){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations},key,256);return b64u(new Uint8Array(bits))}
function safeEqual(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function cookie(request,name){const raw=request.headers.get('cookie')||'';for(const part of raw.split(';')){const [k,...v]=part.trim().split('=');if(k===name)return v.join('=')}return ''}
const setSessionCookie=token=>`${AUTH_COOKIE}=${token}; Path=/; Secure; HttpOnly; SameSite=Strict`;
const clearSessionCookie=()=>`${AUTH_COOKIE}=; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=0`;
async function auditAuth(env,userId,email,action,outcome){if(!env.DB)return;await env.DB.prepare('INSERT INTO crm_auth_audit (id,user_id,email_hint,action,outcome,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),userId||null,String(email||'').slice(0,3).toLowerCase(),action,outcome,new Date().toISOString()).run()}
async function login(request,env){let body;try{body=await request.json()}catch{return json({error:'Solicitud inválida.'},400)}const email=String(body.email||'').trim().toLowerCase().slice(0,160),password=String(body.password||'');if(!email||password.length<8||password.length>256)return json({error:'Credenciales inválidas.'},401);const user=await env.DB.prepare('SELECT id,email,password_salt,password_hash,password_iterations,role,active FROM crm_users WHERE email=?').bind(email).first();if(!user||!user.active){await auditAuth(env,user?.id,email,'login','denied');return json({error:'Credenciales inválidas.'},401)}const calculated=await passwordHash(password,user.password_salt,Math.max(AUTH_ITERATIONS,Number(user.password_iterations)||0));if(!safeEqual(calculated,user.password_hash)){await auditAuth(env,user.id,email,'login','denied');return json({error:'Credenciales inválidas.'},401)}const now=Date.now(),token=b64u(bytes(32)),csrf=b64u(bytes(24)),id=crypto.randomUUID();await env.DB.prepare('INSERT INTO crm_sessions (id,user_id,token_hash,csrf_token,created_at,last_seen_at,expires_at,absolute_expires_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,user.id,await digest(token),csrf,new Date(now).toISOString(),new Date(now).toISOString(),new Date(now+AUTH_IDLE_MS).toISOString(),new Date(now+AUTH_ABSOLUTE_MS).toISOString()).run();await auditAuth(env,user.id,email,'login','success');return json({ok:true},200,{'set-cookie':setSessionCookie(token)})}
async function session(request,env,touch=true){const token=cookie(request,AUTH_COOKIE);if(!token)return null;const row=await env.DB.prepare('SELECT s.id session_id,s.user_id,s.csrf_token,s.expires_at,s.absolute_expires_at,u.email,u.role,u.active FROM crm_sessions s JOIN crm_users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL').bind(await digest(token)).first();if(!row||!row.active||Date.parse(row.expires_at)<=Date.now()||Date.parse(row.absolute_expires_at)<=Date.now())return null;if(touch)await env.DB.prepare('UPDATE crm_sessions SET last_seen_at=?,expires_at=? WHERE id=?').bind(new Date().toISOString(),new Date(Math.min(Date.now()+AUTH_IDLE_MS,Date.parse(row.absolute_expires_at))).toISOString(),row.session_id).run();return row}
async function me(request,env){const s=await session(request,env);return s?json({id:s.user_id,email:s.email,role:s.role,csrf_token:s.csrf_token}):json({error:'No autenticado.'},401)}
async function logout(request,env){const s=await session(request,env,false);if(s){if(!safeEqual(request.headers.get('x-csrf-token')||'',s.csrf_token))return json({error:'Solicitud no autorizada.'},403);await env.DB.prepare('UPDATE crm_sessions SET revoked_at=? WHERE id=?').bind(new Date().toISOString(),s.session_id).run();await auditAuth(env,s.user_id,s.email,'logout','success')}return json({ok:true},200,{'set-cookie':clearSessionCookie()})}

const headers={'content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",'referrer-policy':'no-referrer','x-content-type-options':'nosniff','x-frame-options':'DENY','permissions-policy':'camera=(), microphone=(), geolocation=()','strict-transport-security':'max-age=31536000; includeSubDomains'};
const json=(d,s=200,extra={})=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers,...extra}});
async function authenticated(request,env){const s=await session(request,env);if(!s)return null;return {id:s.user_id,email:s.email,role:s.role,csrf_token:s.csrf_token}}
async function proxy(request,env){if(!env.BACKEND_URL||!env.ADMIN_API_TOKEN||!env.DB)return json({error:'CRM no configurado.'},503);const user=await authenticated(request,env);if(!user)return json({error:'Inicia sesión para acceder al CRM.'},401);const role=user.role;if(request.method!=='GET'){if(role==='LECTURA')return json({error:'Este rol es de solo lectura.'},403);if(!safeEqual(request.headers.get('x-csrf-token')||'',user.csrf_token))return json({error:'Solicitud no autorizada.'},403);}const requestUrl=new URL(request.url);if(requestUrl.pathname==='/api/g3/verification'&&request.method==='POST'&&request.headers.get('origin')!==requestUrl.origin)return json({error:'Origen no permitido.'},403);const url=requestUrl,target=`${env.BACKEND_URL}${url.pathname.replace('/api','/api/admin')}${url.search}`;const init={method:request.method,headers:{authorization:`Bearer ${env.ADMIN_API_TOKEN}`,'x-admin-role':role.toLowerCase(),'x-crm-actor-id':user.id,'content-type':'application/json'}};if(env.BACKEND_SITE_AUTH_TOKEN)init.headers['OAI-Sites-Authorization']=`Bearer ${env.BACKEND_SITE_AUTH_TOKEN}`;if(!['GET','HEAD'].includes(request.method))init.body=await request.text();try{const r=await fetch(target,init);if(!(r.headers.get('content-type')||'').includes('application/json'))return json({error:'El CRM no puede autenticar su conexión privada con el backend de QA.'},502);return new Response(r.body,{status:r.status,headers:{'content-type':r.headers.get('content-type')||'application/json','cache-control':'no-store',...headers}})}catch(e){console.error('proxy failed',e);return json({error:'Backend no disponible.'},503)}}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/auth/login'&&request.method==='POST')return login(request,env);if(url.pathname==='/api/auth/me'&&request.method==='GET')return me(request,env);if(url.pathname==='/api/auth/logout'&&request.method==='POST')return logout(request,env);if(url.pathname.startsWith('/api/'))return proxy(request,env);const asset=ASSETS[url.pathname]||ASSETS['/'];return new Response(asset.body,{headers:{'content-type':asset.type,'cache-control':['/','/index.html','/styles.css','/crm.js','/reminders.js','/g3-flow.js'].includes(url.pathname)?'no-cache':'public, max-age=3600',...headers}})}};
