import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const workflow = await readFile('.github/workflows/qa-appointment-reminders.yml', 'utf8');
const source = workflow.split("node --input-type=module <<'JAVASCRIPT'\n")[1].split('\n          JAVASCRIPT')[0].split('\n').map(line => line.slice(10)).join('\n').split("await mkdir('evidence'")[0];
const { bearer, run } = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
assert.equal(bearer(' Bearer abc.def ', 'TOKEN'), 'Bearer abc.def');
assert.equal(bearer('abc.def', 'TOKEN'), 'Bearer abc.def');
for (const bad of ['', 'Bearer Bearer abc', 'abc\n', '"abc"', 'abc def']) assert.throws(() => bearer(bad,'TOKEN'));
const env = { SITES_QA_AUTHORIZATION:'Bearer site.test', REMINDER_TRIGGER_TOKEN:'trigger.test' };
let evidence, calls=[];
const save=async (path,value)=>{ evidence=JSON.parse(value); };
const log=()=>{};
const response=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}});
await assert.rejects(run(env,async (url,options)=>{ calls.push({url,options}); return response({},401); },save,log),/SITE_AUTH_HTTP_401/);
assert.equal(calls.length,1);
assert.equal(evidence.site_auth_http_status,401);
calls=[];
await run({...env,AUTH_ONLY:'true'},async (url,options)=>{ calls.push({url,options}); return response({ok:true,service:'salvacion-m'}); },save,log);
assert.equal(calls.length,1);
assert.equal(evidence.result,'AUTHENTICATED_NO_SEND');
calls=[];
await run(env,async (url,options)=>{calls.push({url,options}); return response(calls.length===1?{ok:true,service:'salvacion-m'}:{ok:true,queued:1,sent:1,failed:0,duplicates:0,run_id:'test-123'});},save,log);
assert.equal(calls.length,2);
assert.equal(calls[0].options.headers.Authorization,undefined);
assert.equal(calls[1].options.headers.Authorization,'Bearer trigger.test');
assert.equal(calls[1].options.headers['OAI-Sites-Authorization'],'Bearer site.test');
assert.equal(calls[1].options.redirect,'error');
assert.equal(evidence.dispatch.sent,1);
calls=[];
await assert.rejects(run(env,async (url,options)=>{calls.push(url); if(calls.length===1)return response({ok:true,service:'salvacion-m'});throw new Error('sensitive provider details');},save,log),/NETWORK_TIMEOUT_OR_REDIRECT/);
assert.equal(calls.length,2);
assert.ok(!JSON.stringify(evidence).includes('sensitive'));
assert.ok(!JSON.stringify(evidence).includes('site.test'));
console.log('PASS: validation, 401 stops POST, auth-only, headers, success evidence, no retries or secret leakage');
